import Head from "next/head";
import Navbar from "./components/Navbar";
import DonateForm from "./components/DonateForm";

export default function Donation() {
  return (
    <div>
      <Head>
        <title>Sick Pay Solidarity Fund</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/3ce30db80b.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <Navbar />
      <DonateForm />
    </div>
  );
}
